"""Build the page from template.html.

Writes:
  index.html          standalone page for GitHub Pages
  artifact.html       fragment for the Claude artifact (the host adds its own <head>)
  data/eastbound.sql  public SQL export of the rate and tariff data (SQLite/MySQL/Dolt)
"""
import json
import sys
from datetime import date
from pathlib import Path

from pipeline import validate

here = Path(__file__).parent
data = here / "data"
problems = validate.run()
for w in problems.warnings:
    print("warning:", w)
if problems.errors:
    sys.exit("Data errors, not building:\n  " + "\n  ".join(problems.errors))

rates = json.loads((data / "rates.json").read_text())
tariffs = json.loads((data / "tariffs.json").read_text())

body = (here / "template.html").read_text()
body = body.replace("__WORLD__", (data / "world-110m.json").read_text())
body = body.replace("__US__", (data / "states-10m.json").read_text())
body = body.replace("__RATES__", json.dumps(rates, ensure_ascii=False))
body = body.replace("__TARIFFS__", json.dumps(tariffs, ensure_ascii=False))
body = body.replace("__CALC__", (here / "calc.js").read_text())
nice = lambda d: date.fromisoformat(d).strftime("%b %-d, %Y")
body = body.replace("__RATES_ASOF__", nice(rates["as_of"])).replace("__TARIFFS_ASOF__", nice(tariffs["as_of"]))
# Rate source lines in "About & sources", generated so the weekly rate update keeps them current
body = body.replace("<!--RATE_SOURCES-->", "\n".join(
    f'<li><a href="{r["url"]}">{r["source"]}, {nice(r["date"])}</a>: {r["lane"]} '
    + (f'${r["usd"]:.2f}/kg' if r["unit"] == "per kg" else f'${r["usd"]:,.0f} {r["unit"]}') + "</li>"
    for r in rates["ocean_fcl40"] + rates["air"]))
left = [k for k in ("__WORLD__", "__US__", "__RATES__", "__TARIFFS__", "__CALC__", "<!--RATE_SOURCES-->") if k in body]
if left:
    sys.exit(f"Placeholders not filled: {left}")

(here / "artifact.html").write_text(body)
(here / "index.html").write_text(
    '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    "<style>body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n"
    + body
    + "\n</html>\n"
)


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


sql = [
    "-- Eastbound 3PL Index: public freight rate and US tariff data",
    f"-- Rates as of {rates['as_of']}, tariffs as of {tariffs['as_of']}. Generated by build.py; edit data/*.json instead.",
    "",
    "CREATE TABLE freight_rates (lane_origin VARCHAR(8), lane VARCHAR(120), mode VARCHAR(16), usd DECIMAL(12,2), unit VARCHAR(40),",
    "  observed DATE, kind VARCHAR(40), source VARCHAR(120), url VARCHAR(300), used_in_site BOOLEAN);",
]
for group, mode, used in (("ocean_fcl40", "ocean_fcl40", True), ("reference", "ocean_fcl40", False), ("air", "air", True)):
    for r in rates[group]:
        sql.append("INSERT INTO freight_rates VALUES (" + ", ".join(q(x) for x in (
            r["origin"], r["lane"], mode, r["usd"], r["unit"], r["date"], r["kind"], r["source"], r["url"], used)) + ");")
sql += ["", "CREATE TABLE tariff_countries (code VARCHAR(4) PRIMARY KEY, name VARCHAR(40), forced_labor_301_pct DECIMAL(5,2));"]
for code, c in tariffs["countries"].items():
    sql.append(f"INSERT INTO tariff_countries VALUES ({q(code)}, {q(c['name'])}, {q(c['forced_labor_301'])});")
sql += ["", "CREATE TABLE tariff_products (hts VARCHAR(12), sector VARCHAR(20), name VARCHAR(80), mfn_pct DECIMAL(5,2),",
        "  china_301_pct DECIMAL(5,2), section_232_pct DECIMAL(5,2), adcvd_possible BOOLEAN, note VARCHAR(300));"]
for p in tariffs["products"]:
    sql.append("INSERT INTO tariff_products VALUES (" + ", ".join(q(x) for x in (
        p["hts"], p["sector"], p["name"], p["mfn"], p["cn301"], p["s232"], p.get("adcvd", False), p["note"])) + ");")
f = tariffs["fees"]
sql += ["", "CREATE TABLE customs_fees (fee VARCHAR(8), rate_pct DECIMAL(7,4), min_usd DECIMAL(10,2), max_usd DECIMAL(10,2), note VARCHAR(120));",
        f"INSERT INTO customs_fees VALUES ('MPF', {f['mpf_rate']}, {f['mpf_min']}, {f['mpf_max']}, {q(f['mpf_note'])});",
        f"INSERT INTO customs_fees VALUES ('HMF', {f['hmf_rate']}, NULL, NULL, {q(f['hmf_note'])});", ""]
(data / "eastbound.sql").write_text("\n".join(sql))
print("built index.html, artifact.html, data/eastbound.sql")
