"""Build the page from template.html.

Writes:
  index.html          standalone page for GitHub Pages
  artifact.html       fragment for the Claude artifact (the host adds its own <head>)
  data/eastbound.sql  public SQL export of the rate and tariff data (SQLite/MySQL/Dolt)
"""
import json
from pathlib import Path

here = Path(__file__).parent
data = here / "data"
rates = json.loads((data / "rates.json").read_text())
tariffs = json.loads((data / "tariffs.json").read_text())

body = (here / "template.html").read_text()
body = body.replace("__WORLD__", (data / "world-110m.json").read_text())
body = body.replace("__US__", (data / "states-10m.json").read_text())
body = body.replace("__RATES__", json.dumps(rates, ensure_ascii=False))
body = body.replace("__TARIFFS__", json.dumps(tariffs, ensure_ascii=False))

(here / "artifact.html").write_text(body)
(here / "index.html").write_text(
    '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
    "<style>body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>\n"
    + body
    + "\n</html>\n"
)


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


sql = [
    "-- Eastbound 3PL Index: public freight rate and US tariff data",
    f"-- Rates as of {rates['as_of']}, tariffs as of {tariffs['as_of']}. Generated by build.py; edit data/*.json instead.",
    "",
    "CREATE TABLE freight_rates (lane_origin VARCHAR(8), lane VARCHAR(120), mode VARCHAR(16), usd DECIMAL(12,2), unit VARCHAR(40),",
    "  observed DATE, kind VARCHAR(40), source VARCHAR(120), url VARCHAR(300), used_in_site BOOLEAN);",
]
for group, mode, used in (("ocean_fcl40", "ocean_fcl40", True), ("reference", "ocean_fcl40", False), ("air", "air", True)):
    for r in rates[group]:
        sql.append("INSERT INTO freight_rates VALUES (" + ", ".join(q(x) for x in (
            r["origin"], r["lane"], mode, r["usd"], r["unit"], r["date"], r["kind"], r["source"], r["url"], used)) + ");")
sql += ["", "CREATE TABLE tariff_countries (code VARCHAR(4) PRIMARY KEY, name VARCHAR(40), forced_labor_301_pct DECIMAL(5,2));"]
for code, c in tariffs["countries"].items():
    sql.append(f"INSERT INTO tariff_countries VALUES ({q(code)}, {q(c['name'])}, {q(c['forced_labor_301'])});")
sql += ["", "CREATE TABLE tariff_products (hts VARCHAR(12), sector VARCHAR(20), name VARCHAR(80), mfn_pct DECIMAL(5,2),",
        "  china_301_pct DECIMAL(5,2), section_232_pct DECIMAL(5,2), adcvd_possible BOOLEAN, note VARCHAR(300));"]
for p in tariffs["products"]:
    sql.append("INSERT INTO tariff_products VALUES (" + ", ".join(q(x) for x in (
        p["hts"], p["sector"], p["name"], p["mfn"], p["cn301"], p["s232"], p.get("adcvd", False), p["note"])) + ");")
f = tariffs["fees"]
sql += ["", "CREATE TABLE customs_fees (fee VARCHAR(8), rate_pct DECIMAL(7,4), min_usd DECIMAL(10,2), max_usd DECIMAL(10,2), note VARCHAR(120));",
        f"INSERT INTO customs_fees VALUES ('MPF', {f['mpf_rate']}, {f['mpf_min']}, {f['mpf_max']}, {q(f['mpf_note'])});",
        f"INSERT INTO customs_fees VALUES ('HMF', {f['hmf_rate']}, NULL, NULL, {q(f['hmf_note'])});", ""]
(data / "eastbound.sql").write_text("\n".join(sql))
print("built index.html, artifact.html, data/eastbound.sql")
