-- Eastbound 3PL Index: public freight rate and US tariff data
-- Rates as of 2026-10-01, tariffs as of 2026-10-05. Generated by build.py; edit data/*.json instead.

CREATE TABLE freight_rates (lane_origin VARCHAR(8), lane VARCHAR(120), mode VARCHAR(16), usd DECIMAL(12,2), unit VARCHAR(40),
  observed DATE, kind VARCHAR(40), source VARCHAR(120), url VARCHAR(300), used_in_site BOOLEAN);
INSERT INTO freight_rates VALUES ('cn', 'Shanghai → New York', 'ocean_fcl40', 10428, 'per 40'' container', '2026-10-01', 'Published index', 'Drewry World Container Index', 'https://www.thedcn.com.au/news/world-container-index-1-october-2026', 1);
INSERT INTO freight_rates VALUES ('vn', 'China / East Asia → US East Coast (FBX03)', 'ocean_fcl40', 9600, 'per 40'' container', '2026-09-30', 'Published index', 'Freightos Baltic Index FBX03', 'https://www.freightos.com/freight-resources/china-us-truce-to-reduce-some-tariffs-and-likely-postpone-port-fees-september-30-2026-update/', 1);
INSERT INTO freight_rates VALUES ('in', 'Nhava Sheva → New York (40'' high cube)', 'ocean_fcl40', 12600, 'per 40'' container', '2026-09-15', 'Lowest published carrier rate', 'Skypace carrier rate listing', 'https://skypace.com/ocean-freight/rates/nhava-sheva-(jnpt)-to-new-york', 1);
INSERT INTO freight_rates VALUES ('cn', 'China / East Asia → US East Coast (FBX03)', 'ocean_fcl40', 9600, 'per 40'' container', '2026-09-30', 'Published index', 'Freightos Baltic Index FBX03', 'https://www.freightos.com/freight-resources/china-us-truce-to-reduce-some-tariffs-and-likely-postpone-port-fees-september-30-2026-update/', 0);
INSERT INTO freight_rates VALUES ('cn', 'Shanghai → Los Angeles', 'ocean_fcl40', 7835, 'per 40'' container', '2026-10-01', 'Published index', 'Drewry World Container Index', 'https://www.thedcn.com.au/news/world-container-index-1-october-2026', 0);
INSERT INTO freight_rates VALUES ('vn', 'Vietnam → US East Coast', 'ocean_fcl40', 9000, 'per 40'' container (approx.)', '2026-07-13', 'News report', 'Tuoi Tre News', 'https://news.tuoitre.vn/vietnam-us-container-freight-rates-surge-to-nearly-9000-per-container-103260713123316834.htm', 0);
INSERT INTO freight_rates VALUES ('*', 'Far East → USA', 'air', 6.3, 'per kg', '2026-09-08', 'Published index', 'Freightos Air Index (FAX)', 'https://www.stattimes.com/air-cargo/global-air-cargo-rates-ease-after-peak-season-freightos-data-shows-1357688', 1);

CREATE TABLE tariff_countries (code VARCHAR(4) PRIMARY KEY, name VARCHAR(40), forced_labor_301_pct DECIMAL(5,2));
INSERT INTO tariff_countries VALUES ('cn', 'China', 12.5);
INSERT INTO tariff_countries VALUES ('vn', 'Vietnam', 12.5);
INSERT INTO tariff_countries VALUES ('in', 'India', 10);

CREATE TABLE tariff_products (hts VARCHAR(12), sector VARCHAR(20), name VARCHAR(80), mfn_pct DECIMAL(5,2),
  china_301_pct DECIMAL(5,2), section_232_pct DECIMAL(5,2), adcvd_possible BOOLEAN, note VARCHAR(300));
INSERT INTO tariff_products VALUES ('6109.10.00', 'Apparel', 'Cotton knit T-shirts', 16.5, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('6203.42.40', 'Apparel', 'Men''s cotton trousers', 16.6, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('6110.30.30', 'Apparel', 'Synthetic-fiber sweaters', 32, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('0306.17', 'Food', 'Frozen shrimp and prawns', 0, 25, 0, 1, 'Antidumping duties on frozen warmwater shrimp from China, India and Vietnam may apply. China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('0904.11', 'Food', 'Black pepper, whole', 0, 25, 0, 0, 'China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('1905.90', 'Food', 'Baked goods (bread, pastry, biscuits)', 0, 25, 0, 0, 'FDA Prior Notice required. China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('8542.31', 'Defense', 'Processors and controllers (ICs)', 0, 50, 0, 0, 'China 301 raised to 50% in the 2024 review. A 25% Section 232 duty hits certain logic ICs, with wide exemptions. ITAR/EAR may apply.');
INSERT INTO tariff_products VALUES ('7208', 'Defense', 'Hot-rolled steel plate', 0, 25, 50, 0, 'Section 232 steel at 50%. Section 232 goods are exempt from the forced-labor 301 duty.');
INSERT INTO tariff_products VALUES ('7616.99', 'Defense', 'Aluminum parts and articles', 2.5, 25, 50, 0, 'Section 232 aluminum derivative. Verify that the HTS line is in scope.');

CREATE TABLE customs_fees (fee VARCHAR(8), rate_pct DECIMAL(7,4), min_usd DECIMAL(10,2), max_usd DECIMAL(10,2), note VARCHAR(120));
INSERT INTO customs_fees VALUES ('MPF', 0.3464, 34.58, 670.86, 'FY2027 limits, entries on or after Oct 1, 2026');
INSERT INTO customs_fees VALUES ('HMF', 0.125, NULL, NULL, 'Ocean cargo only');
