-- Eastbound 3PL Index: public freight rate, US tariff and 3PL provider data
-- Rates as of 2026-10-01, tariffs as of 2026-10-05. Generated by build.py; edit data/*.json instead.

CREATE TABLE freight_rates (lane_origin VARCHAR(8), lane VARCHAR(120), mode VARCHAR(16), usd DECIMAL(12,2), unit VARCHAR(40),
  observed DATE, kind VARCHAR(40), source VARCHAR(120), url VARCHAR(300), used_in_site BOOLEAN);
INSERT INTO freight_rates VALUES ('cn', 'Shanghai → New York', 'ocean_fcl40', 10428, 'per 40'' container', '2026-10-01', 'Published index', 'Drewry World Container Index', 'https://www.thedcn.com.au/news/world-container-index-1-october-2026', 1);
INSERT INTO freight_rates VALUES ('vn', 'China / East Asia → US East Coast (FBX03)', 'ocean_fcl40', 9600, 'per 40'' container', '2026-09-30', 'Published index', 'Freightos Baltic Index FBX03', 'https://www.freightos.com/freight-resources/china-us-truce-to-reduce-some-tariffs-and-likely-postpone-port-fees-september-30-2026-update/', 1);
INSERT INTO freight_rates VALUES ('in', 'Nhava Sheva → New York (40'' high cube)', 'ocean_fcl40', 12600, 'per 40'' container', '2026-09-15', 'Lowest published carrier rate', 'Skypace carrier rate listing', 'https://skypace.com/ocean-freight/rates/nhava-sheva-(jnpt)-to-new-york', 1);
INSERT INTO freight_rates VALUES ('cn', 'China / East Asia → US East Coast (FBX03)', 'ocean_fcl40', 9600, 'per 40'' container', '2026-09-30', 'Published index', 'Freightos Baltic Index FBX03', 'https://www.freightos.com/freight-resources/china-us-truce-to-reduce-some-tariffs-and-likely-postpone-port-fees-september-30-2026-update/', 0);
INSERT INTO freight_rates VALUES ('cn', 'Shanghai → Los Angeles', 'ocean_fcl40', 7835, 'per 40'' container', '2026-10-01', 'Published index', 'Drewry World Container Index', 'https://www.thedcn.com.au/news/world-container-index-1-october-2026', 0);
INSERT INTO freight_rates VALUES ('vn', 'Vietnam → US East Coast', 'ocean_fcl40', 9000, 'per 40'' container (approx.)', '2026-07-13', 'News report', 'Tuoi Tre News', 'https://news.tuoitre.vn/vietnam-us-container-freight-rates-surge-to-nearly-9000-per-container-103260713123316834.htm', 0);
INSERT INTO freight_rates VALUES ('*', 'Far East → USA', 'air', 6.3, 'per kg', '2026-09-08', 'Published index', 'Freightos Air Index (FAX)', 'https://www.stattimes.com/air-cargo/global-air-cargo-rates-ease-after-peak-season-freightos-data-shows-1357688', 1);

CREATE TABLE tariff_countries (code VARCHAR(4) PRIMARY KEY, name VARCHAR(40), forced_labor_301_pct DECIMAL(5,2));
INSERT INTO tariff_countries VALUES ('cn', 'China', 12.5);
INSERT INTO tariff_countries VALUES ('vn', 'Vietnam', 12.5);
INSERT INTO tariff_countries VALUES ('in', 'India', 10);

CREATE TABLE tariff_products (hts VARCHAR(12), sector VARCHAR(20), name VARCHAR(80), mfn_pct DECIMAL(5,2),
  china_301_pct DECIMAL(5,2), section_232_pct DECIMAL(5,2), adcvd_possible BOOLEAN, note VARCHAR(300));
INSERT INTO tariff_products VALUES ('6109.10.00', 'Apparel', 'Cotton knit T-shirts', 16.5, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('6203.42.40', 'Apparel', 'Men''s cotton trousers', 16.6, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('6110.30.30', 'Apparel', 'Synthetic-fiber sweaters', 32, 7.5, 0, 0, 'China Section 301 List 4A.');
INSERT INTO tariff_products VALUES ('0306.17', 'Food', 'Frozen shrimp and prawns', 0, 25, 0, 1, 'Antidumping duties on frozen warmwater shrimp from China, India and Vietnam may apply. China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('0904.11', 'Food', 'Black pepper, whole', 0, 25, 0, 0, 'China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('1905.90', 'Food', 'Baked goods (bread, pastry, biscuits)', 0, 25, 0, 0, 'FDA Prior Notice required. China 301 rate: verify.');
INSERT INTO tariff_products VALUES ('8542.31', 'Defense', 'Processors and controllers (ICs)', 0, 50, 0, 0, 'China 301 raised to 50% in the 2024 review. A 25% Section 232 duty hits certain logic ICs, with wide exemptions. ITAR/EAR may apply.');
INSERT INTO tariff_products VALUES ('7208', 'Defense', 'Hot-rolled steel plate', 0, 25, 50, 0, 'Section 232 steel at 50%. Section 232 goods are exempt from the forced-labor 301 duty.');
INSERT INTO tariff_products VALUES ('7616.99', 'Defense', 'Aluminum parts and articles', 2.5, 25, 50, 0, 'Section 232 aluminum derivative. Verify that the HTS line is in scope.');

CREATE TABLE customs_fees (fee VARCHAR(8), rate_pct DECIMAL(7,4), min_usd DECIMAL(10,2), max_usd DECIMAL(10,2), note VARCHAR(120));
INSERT INTO customs_fees VALUES ('MPF', 0.3464, 34.58, 670.86, 'FY2027 limits, entries on or after Oct 1, 2026');
INSERT INTO customs_fees VALUES ('HMF', 0.125, NULL, NULL, 'Ocean cargo only');

-- Providers as of 2026-10-06. serves: 'small' takes small and mid-size brands, 'large' is mostly large shippers.
CREATE TABLE providers (name VARCHAR(80) PRIMARY KEY, type VARCHAR(40), serves VARCHAR(8), na_warehouse_sqft_m DECIMAL(6,1),
  min_volume VARCHAR(120), website VARCHAR(300), verified BOOLEAN, note VARCHAR(300));
CREATE TABLE provider_hubs (provider VARCHAR(80), metro VARCHAR(40), lat DECIMAL(7,4), lon DECIMAL(7,4));
INSERT INTO providers VALUES ('DHL Supply Chain', 'Contract logistics', 'large', 163.0, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('DHL Supply Chain', 'Lehigh Valley PA', 40.6, -75.49);
INSERT INTO provider_hubs VALUES ('DHL Supply Chain', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('DHL Supply Chain', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('DHL Supply Chain', 'Baltimore MD', 39.29, -76.61);
INSERT INTO providers VALUES ('Ryder', 'Contract logistics', 'large', 105.0, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('Ryder', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('Ryder', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('Ryder', 'South Florida', 26.12, -80.14);
INSERT INTO providers VALUES ('GXO', 'Contract logistics', 'large', 83.7, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('GXO', 'Lehigh Valley PA', 40.6, -75.49);
INSERT INTO provider_hubs VALUES ('GXO', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('GXO', 'Atlanta GA', 33.75, -84.39);
INSERT INTO providers VALUES ('NFI', 'Contract logistics', 'large', 70.0, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('NFI', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('NFI', 'Lehigh Valley PA', 40.6, -75.49);
INSERT INTO provider_hubs VALUES ('NFI', 'Savannah GA', 32.08, -81.09);
INSERT INTO providers VALUES ('GEODIS', 'Contract logistics', 'large', 50.0, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('GEODIS', 'Lehigh Valley PA', 40.6, -75.49);
INSERT INTO provider_hubs VALUES ('GEODIS', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('GEODIS', 'Charlotte NC', 35.23, -80.84);
INSERT INTO providers VALUES ('Kenco', 'Contract logistics', 'large', 45.9, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('Kenco', 'Chattanooga TN', 35.05, -85.31);
INSERT INTO provider_hubs VALUES ('Kenco', 'Atlanta GA', 33.75, -84.39);
INSERT INTO providers VALUES ('DSV', 'Forwarder + warehousing', 'large', 45.3, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('DSV', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('DSV', 'Savannah GA', 32.08, -81.09);
INSERT INTO provider_hubs VALUES ('DSV', 'Atlanta GA', 33.75, -84.39);
INSERT INTO providers VALUES ('FedEx Logistics', 'Contract logistics', 'large', 38.8, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('FedEx Logistics', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('FedEx Logistics', 'Lehigh Valley PA', 40.6, -75.49);
INSERT INTO providers VALUES ('Saddle Creek', 'Contract logistics', 'large', 31.0, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('Saddle Creek', 'Lakeland FL', 28.04, -81.95);
INSERT INTO provider_hubs VALUES ('Saddle Creek', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('Saddle Creek', 'Charlotte NC', 35.23, -80.84);
INSERT INTO providers VALUES ('Flexport', 'Forwarder + warehousing', 'small', NULL, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('Flexport', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('Flexport', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('Flexport', 'Savannah GA', 32.08, -81.09);
INSERT INTO providers VALUES ('ShipBob', 'E-commerce fulfillment', 'small', NULL, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('ShipBob', 'Central NJ', 40.31, -74.51);
INSERT INTO provider_hubs VALUES ('ShipBob', 'Atlanta GA', 33.75, -84.39);
INSERT INTO providers VALUES ('ShipMonk', 'E-commerce fulfillment', 'small', NULL, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('ShipMonk', 'South Florida', 26.12, -80.14);
INSERT INTO provider_hubs VALUES ('ShipMonk', 'Central NJ', 40.31, -74.51);
INSERT INTO providers VALUES ('Red Stag Fulfillment', 'E-commerce fulfillment', 'small', NULL, NULL, NULL, 0, 'Bulky / heavy items');
INSERT INTO provider_hubs VALUES ('Red Stag Fulfillment', 'Sweetwater TN', 35.6, -84.46);
INSERT INTO providers VALUES ('Stord', 'E-commerce fulfillment', 'small', NULL, NULL, NULL, 0, NULL);
INSERT INTO provider_hubs VALUES ('Stord', 'Atlanta GA', 33.75, -84.39);
INSERT INTO provider_hubs VALUES ('Stord', 'Lehigh Valley PA', 40.6, -75.49);
